name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.name "David Lansky"
          git config --global user.email "dlansky@gmail.com"
          git remote add hf https://dlansky:${HF_TOKEN}@huggingface.co/spaces/DLansky/Stretching-Timer
          git push --force hf main
