name: Deploy to Hugging Face

on:
  push:
    branches: [main]          # change if you deploy from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1⃣  Grab the latest commit of this GitHub repo
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2⃣  Clone the Hugging Face Space (nuke any old clone first)
    - name: Clone HF Space
      run: |
        rm -rf hf-space                                  # clean workspace on re-runs
        git clone https://DLansky:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/DLansky/Stretching-Timer hf-space

    # 3⃣  Sync all project files into that clone (mirror deletions)
    - name: Sync files
      run: |
        rsync -av --delete --exclude ".git/" --exclude "hf-space/" ./ hf-space/

    # 4⃣  Commit & push only when changes exist
    - name: Push to HF
      run: |
        cd hf-space
        git config user.email "actions@github.com"
        git config user.name  "GitHub Actions"
        if ! git diff --quiet; then
          git add .
          git commit -m "Auto-deploy $GITHUB_SHA"
          git push origin main
        else
          echo "No changes to deploy."
        fi
